require("user.impatient")
require("user.options")
require("user.keymaps")
require("user.plugins")
require("user.colorscheme")
require("user.better-escape")
require("user.cmp")
require("user.lsp")
require("user.telescope")
require("user.treesitter")
require("user.autopairs")
require("user.comment")
require("user.gitsigns")
require("user.nvim-tree")
require("user.bufferline")
require("user.lualine")
require("user.toggleterm")
require("user.project")
require("user.indentline")
require("user.alpha")
require("user.autocommands")
require("user.code-runner")
require("user.colorizer")
require("user.todo-comments")
require("user.autosave")
require("user.auto-session")
require("user.modes")
require("user.auto-session")
require("user.cheatsheet")
-- require("user.renamer")
vim.cmd("source ~/.config/nvim/lua/user/firenvim.vim")
-- vim.cmd("imap <Esc> <Plug>CapsLockToggle")
-- vim.cmd("g:leetcode_solution_filetype python")
-- vim.g['leetcode_lang'] = 'python'
-- vim.g['leetcode_root_dir'] = '/mnt/hdd/myProjects/python_101/leetcode'
vim.g['python3_host_prog'] = '~/.config/pyenv/shims/python3'


-- require("firenvim").setup()

